version: '2'
services:
  python:
    networks:
      - amazeeio-network
      - default
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      lagoon.type: node # just for now, there is no python yet
    volumes:
      - .:/app:delegated
    environment:
      - AMAZEEIO_URL=python.docker.amazee.io
      - AMAZEEIO=AMAZEEIO
      - AMAZEEIO_HTTP_PORT=3000
      - LAGOON_ROUTE=http://python.docker.amazee.io
      - AMAZEEIO_SITENAME
      - AMAZEEIO_DB_HOST
      - AMAZEEIO_DB_USERNAME
      - AMAZEEIO_DB_PASSWORD
      - AMAZEEIO_DB_PORT
      - AMAZEEIO_REDIS_HOST
      - AMAZEEIO_REDIS_PORT
      - AMAZEEIO_POSTGRES_HOST
      - AMAZEEIO_POSTGRES_USERNAME
      - AMAZEEIO_POSTGRES_PASSWORD
      - AMAZEEIO_POSTGRES_PORT
    depends_on:
      - mariadb
      - redis
      - postgres
  mariadb:
    image: amazeeio/centos7-mariadb-drupal:10.1
    labels:
      lagoon.type: mariadb
    environment:
      - MYSQL_DATABASE=${AMAZEEIO_SITENAME}
      - MYSQL_USER=${AMAZEEIO_DB_USERNAME}
      - MYSQL_PASSWORD=${AMAZEEIO_DB_PASSWORD}
    volumes:
      - /var/lib/mysql
  redis:
    image: amazeeio/redis
    labels:
      lagoon.type: redis
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=${AMAZEEIO_POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${AMAZEEIO_POSTGRES_PASSWORD}
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres

networks:
  amazeeio-network:
    external: true